require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

FactoryBot/CreateList:
  Exclude:
    - spec/helpers/suid_generator_spec.rb
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/OutputSafety:
  Exclude:
    - app/helpers/csv_helper.rb
Rails/UnknownEnv:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/BeforeAfterAll:
  Exclude:
    - spec/features/export_spec.rb
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/Semicolon:
  Exclude:
    - config/routes.rb
Style/SlicingWithRange:
  Enabled: true
